# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='website',
            field=models.URLField(max_length=2048),
        ),
    ]
